# Generated by Django 3.2 on 2022-05-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Kategoria')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorii',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Imię')),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Foto')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Ostatnie zmiany')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.category')),
            ],
            options={
                'verbose_name': 'Słynne kobiety',
                'verbose_name_plural': 'Słynne kobiety',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
