# Generated by Django 3.2 on 2022-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20220511_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorii'},
        ),
        migrations.AlterModelOptions(
            name='woman',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Słynne kobiety', 'verbose_name_plural': 'Słynne kobiety'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnie zmiany'),
        ),
        migrations.AlterField(
            model_name='woman',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Imię'),
        ),
    ]
